<?php
/**
 * Created by PhpStorm.
 * User: tik_squad
 * Date: 10/10/19
 * Time: 11:10 AM
 */

namespace DedeGunawan\VaBtnUnsil2\Requests;


class CreateRequest extends BaseRequest
{
    protected $required_columns=[];

    public function toArray()
    {
        $datas = parent::toArray(); // TODO: Change the autogenerated stub
        if (isset($datas['nama'])) $datas['nama'] = substr($datas['nama'], 0, 40);
        return $datas;
    }


}